const ErrorCodes = Object.freeze({

    AUTH: Object.freeze({

        INVALID_OTP: "AUTH.INVALID_OTP",

        OTP_EXPIRED: "AUTH.OTP_EXPIRED",

        INVALID_REFRESH_TOKEN: "AUTH.INVALID_REFRESH_TOKEN",

        SESSION_EXPIRED: "AUTH.SESSION_EXPIRED",

        IDENTITY_NOT_FOUND: "AUTH.IDENTITY_NOT_FOUND",

        IDENTITY_NOT_VERIFIED: "AUTH.IDENTITY_NOT_VERIFIED"

    }),

    USER: Object.freeze({

        NOT_FOUND: "USER.NOT_FOUND",

        USERNAME_ALREADY_EXISTS: "USER.USERNAME_ALREADY_EXISTS",

        PHONE_ALREADY_EXISTS: "USER.PHONE_ALREADY_EXISTS",

        EMAIL_ALREADY_EXISTS: "USER.EMAIL_ALREADY_EXISTS",

        ACCOUNT_SUSPENDED: "USER.ACCOUNT_SUSPENDED",

        ACCOUNT_DEACTIVATED: "USER.ACCOUNT_DEACTIVATED"

    }),

    PAGE: Object.freeze({

        NOT_FOUND: "PAGE.NOT_FOUND",

        ACCESS_DENIED: "PAGE.ACCESS_DENIED",

        SLUG_ALREADY_EXISTS: "PAGE.SLUG_ALREADY_EXISTS"

    }),

    ITINERARY: Object.freeze({

        NOT_FOUND: "ITINERARY.NOT_FOUND"

    }),

    COMMON: Object.freeze({

        VALIDATION_FAILED: "COMMON.VALIDATION_FAILED",

        INTERNAL_SERVER_ERROR: "COMMON.INTERNAL_SERVER_ERROR"

    })

});

export default ErrorCodes;