const ErrorCodes = Object.freeze({

    AUTH: Object.freeze({

        INVALID_OTP: "AUTH.INVALID_OTP",

        OTP_EXPIRED: "AUTH.OTP_EXPIRED",

        INVALID_REFRESH_TOKEN: "AUTH.INVALID_REFRESH_TOKEN",

        SESSION_EXPIRED: "AUTH.SESSION_EXPIRED",

        IDENTITY_NOT_FOUND: "AUTH.IDENTITY_NOT_FOUND",

        IDENTITY_NOT_VERIFIED: "AUTH.IDENTITY_NOT_VERIFIED",

        INVALID_ACCESS_TOKEN: "AUTH.INVALID_ACCESS_TOKEN",


        

    }),

    USER: Object.freeze({

        NOT_FOUND: "USER.NOT_FOUND",

        USERNAME_ALREADY_EXISTS: "USER.USERNAME_ALREADY_EXISTS",

        PHONE_ALREADY_EXISTS: "USER.PHONE_ALREADY_EXISTS",

        EMAIL_ALREADY_EXISTS: "USER.EMAIL_ALREADY_EXISTS",

        ACCOUNT_SUSPENDED: "USER.ACCOUNT_SUSPENDED",

        ACCOUNT_DEACTIVATED: "USER.ACCOUNT_DEACTIVATED"

    }),

 PROFILE: {
  PHOTO_NOT_ALLOWED:
    "PROFILE.PHOTO_NOT_ALLOWED",

  PHOTO_INVALID_TYPE:
    "PROFILE.PHOTO_INVALID_TYPE",

  PHOTO_TOO_LARGE:
    "PROFILE.PHOTO_TOO_LARGE",

  PHOTO_UPLOAD_FAILED:
    "PROFILE.PHOTO_UPLOAD_FAILED",

  COUNTRY_NOT_FOUND:
    "PROFILE.COUNTRY_NOT_FOUND",

  CITY_NOT_FOUND:
    "PROFILE.CITY_NOT_FOUND",

  CITY_COUNTRY_MISMATCH:
    "PROFILE.CITY_COUNTRY_MISMATCH",
},

CONNECTION: Object.freeze({
  TARGET_NOT_AVAILABLE:
    "CONNECTION.TARGET_NOT_AVAILABLE",

  SELF_REQUEST_NOT_ALLOWED:
    "CONNECTION.SELF_REQUEST_NOT_ALLOWED",

  ALREADY_CONNECTED:
    "CONNECTION.ALREADY_CONNECTED",

  REQUEST_ALREADY_RECEIVED:
    "CONNECTION.REQUEST_ALREADY_RECEIVED",

  REQUEST_NOT_FOUND:
    "CONNECTION.REQUEST_NOT_FOUND",

  CONNECTION_NOT_FOUND:
    "CONNECTION.NOT_FOUND",
}),


BLOCK: Object.freeze({
  TARGET_NOT_AVAILABLE:
    "BLOCK.TARGET_NOT_AVAILABLE",

  SELF_BLOCK_NOT_ALLOWED:
    "BLOCK.SELF_BLOCK_NOT_ALLOWED",
}),

CITY: Object.freeze({
  NOT_FOUND:
    "CITY.NOT_FOUND",
}),

MEMORY: Object.freeze({
  ASSET_NOT_ALLOWED:
    "MEMORY.ASSET_NOT_ALLOWED",

  MEDIA_REQUIRED:
    "MEMORY.MEDIA_REQUIRED",

  MEDIA_INVALID_TYPE:
    "MEMORY.MEDIA_INVALID_TYPE",

  MEDIA_TOO_LARGE:
    "MEMORY.MEDIA_TOO_LARGE",

  MEDIA_UPLOAD_FAILED:
    "MEMORY.MEDIA_UPLOAD_FAILED",
}),

REPORT: Object.freeze({
  TARGET_NOT_AVAILABLE:
    "REPORT.TARGET_NOT_AVAILABLE",

  SELF_REPORT_NOT_ALLOWED:
    "REPORT.SELF_REPORT_NOT_ALLOWED",
}),


VISITED_PLACE: Object.freeze({
  EVIDENCE_REQUIRED:
    "VISITED_PLACE.EVIDENCE_REQUIRED",

  EVIDENCE_INVALID_TYPE:
    "VISITED_PLACE.EVIDENCE_INVALID_TYPE",

  EVIDENCE_TOO_LARGE:
    "VISITED_PLACE.EVIDENCE_TOO_LARGE",

  EVIDENCE_UPLOAD_FAILED:
    "VISITED_PLACE.EVIDENCE_UPLOAD_FAILED",

  PLACE_NOT_AVAILABLE:
    "VISITED_PLACE.PLACE_NOT_AVAILABLE",

  DUPLICATE_EVIDENCE:
    "VISITED_PLACE.DUPLICATE_EVIDENCE",

  EVIDENCE_REJECTED:
    "VISITED_PLACE.EVIDENCE_REJECTED",

  COLLECTION_NOT_FOUND:
    "VISITED_PLACE.COLLECTION_NOT_FOUND",

  COLLECTION_NOT_VERIFIED:
    "VISITED_PLACE.COLLECTION_NOT_VERIFIED",

  PREFERENCE_LIMIT_REACHED:
    "VISITED_PLACE.PREFERENCE_LIMIT_REACHED",
}),

MEDIA: Object.freeze({
  ASSET_NOT_FOUND:
    "MEDIA.ASSET_NOT_FOUND",

  CONTENT_UNAVAILABLE:
    "MEDIA.CONTENT_UNAVAILABLE",
}),


    PAGE: Object.freeze({

        NOT_FOUND: "PAGE.NOT_FOUND",

        ACCESS_DENIED: "PAGE.ACCESS_DENIED",

        SLUG_ALREADY_EXISTS: "PAGE.SLUG_ALREADY_EXISTS"

    }),

    ITINERARY: Object.freeze({

        NOT_FOUND: "ITINERARY.NOT_FOUND"

    }),

    COMMON: Object.freeze({

        VALIDATION_FAILED: "COMMON.VALIDATION_FAILED",

        INTERNAL_SERVER_ERROR: "COMMON.INTERNAL_SERVER_ERROR",

        INVALID_CURSOR:
  "COMMON.INVALID_CURSOR",

    }),
    
 
      
      COMMENT: Object.freeze({
          NOT_FOUND:
    "COMMENT.NOT_FOUND",
        PARENT_NOT_FOUND:
          "COMMENT.PARENT_NOT_FOUND",
        CREATE_FAILED:
          "COMMENT.CREATE_FAILED",
      }),

      POST: Object.freeze({
      NOT_FOUND:
        "POST.NOT_FOUND",

      REACTION_NOT_ALLOWED:
        "POST.REACTION_NOT_ALLOWED",

      CREATE_FAILED:
        "POST.CREATE_FAILED",

      PLACE_NOT_ALLOWED:
        "POST.PLACE_NOT_ALLOWED",

      ASSET_NOT_ALLOWED:
        "POST.ASSET_NOT_ALLOWED",

      ITINERARY_NOT_ALLOWED:
        "POST.ITINERARY_NOT_ALLOWED",

      TAGGED_USER_NOT_ALLOWED:
        "POST.TAGGED_USER_NOT_ALLOWED",

      MEDIA_INVALID_TYPE:
        "POST.MEDIA_INVALID_TYPE",

      MEDIA_TOO_LARGE:
        "POST.MEDIA_TOO_LARGE",

      MEDIA_UPLOAD_FAILED:
        "POST.MEDIA_UPLOAD_FAILED",
    }),


});

export default ErrorCodes;
